import { Metadata } from "next";
import { Suspense } from "react";
import Loading from "../loading";

export const metadata: Metadata = {
  title: "GPH Realty",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Suspense fallback={<Loading />}>
        <main className="w-full min-h-dvh bg-red-500">{children}</main>
      </Suspense>
    </>
  );
}
