import { Metadata } from "next";

export const metadata: Metadata = {
  title: "GPH Realty",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="w-full min-h-dvh flex items-center justify-center bg-[#f9f9f9]">
        <div className="px-3 mx-auto w-full">
          <div></div>
          <div className="grid lg:grid-cols-12 ">
            <div className="lg:col-span-5 mx-auto max-w-full lg:w-[70%] grid items-center">
              <div className="shadow-custom rounded-lg my-[30px] relative flex flex-col bg-white">
                {children}
              </div>
            </div>
            <div className="lg:col-span-7 hidden md:block h-dvh bg-white bg-no-repeat bg-cover bg-review-bg"></div>
          </div>
        </div>
      </div>
    </div>
  );
}
