import Footer from "@/components/shared/footer/Footer";
import Header from "@/components/shared/header/Header";
import ScrollToTop from "@/components/ui/ScrollToTop";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import "../globals.scss";
import { Suspense } from "react";
import Loading from "../loading";

export const metadata: Metadata = {
  title: "GPH Realty",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NextTopLoader color="#EE6C0E" showSpinner={false} />
      <Suspense fallback={<Loading />}>
        <Header />
        <main className="w-full min-h-dvh">{children}</main>
        <ScrollToTop />
        <Footer />
      </Suspense>
    </>
  );
}
