import { Metadata } from "next";
import AdminSidebar from "./components/AdminSidebar";
import { SidebarProvider } from "./components/ui/Sidebar";
import AdminHeader from "./components/AdminHeader";

export const metadata: Metadata = {
  title: "Admin | GPH Realty",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AdminSidebar />
      <main className="w-full min-h-dvh lg:pl-[16rem] ">
        <AdminHeader />
        <div className="w-full h-full flex-1 p-4">{children}</div>
      </main>
    </SidebarProvider>
  );
}
