import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Header from "@/components/shared/header/Header";
import StoreProvider from "@/providers/StoreProvider";
import { Toaster } from "@/components/ui/Toaster";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader color="#EE6C0E" showSpinner={false} />
        <StoreProvider>
          <Header />
          <main>{children}</main>
          <Toaster position="top-center" />
        </StoreProvider>
      </body>
    </html>
  );
}
