import Footer from "@/components/shared/footer/Footer";
import Header from "@/components/shared/header/Header";
import ScrollToTop from "@/components/ui/ScrollToTop";
import { Toaster } from "@/components/ui/Toaster";
import StoreProvider from "@/providers/StoreProvider";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import "./globals.scss";

export const metadata: Metadata = {
  title: "GPH Realty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-montserrat antialiased`}
      >
        <NextTopLoader color="#EE6C0E" showSpinner={false} />
        <StoreProvider>
          <Header />
          <main className="w-full min-h-dvh">{children}</main>
          <ScrollToTop />
          <Footer />
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
