import { Toaster } from "@/components/ui/Toaster";
import SessionProvider from "@/providers/SessionProvider";
import StoreProvider from "@/providers/StoreProvider";
import type { Metadata } from "next";
import { getSession } from "next-auth/react";
import NextTopLoader from "nextjs-toploader";
import "./globals.scss";

export const metadata: Metadata = {
  title: "GPH Realty",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-montserrat antialiased`}>
        <NextTopLoader color="#EE6C0E" showSpinner={false} />
        <SessionProvider session={session!}>
          <StoreProvider>
            <main>{children}</main>
            <Toaster />
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
